In [1]:
import pandas as pd
import numpy as np
import os # Operating System
import numpy as np
import pandas as pd
import datetime as dt # Datetime
import json # library to handle JSON files

#!conda install -c conda-forge geopy --yes
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

#!conda install -c conda-forge folium=0.5.0 --yes
import folium #import folium # map rendering library

In [2]:
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import numpy as np
import holoviews as hv
import geoviews as gv
import datashader as ds
import dask.dataframe as dd
from cartopy import crs
import missingno as msno
import bokeh as bk
from datashader.bokeh_ext import InteractiveImage
from IPython.display import display
pd.options.display.max_columns = None
import re
import multiprocessing as mp
import datashader.transfer_functions as tf
from datashader.utils import lnglat_to_meters as webm
from datetime import datetime
from holoviews.operation.datashader import datashade, dynspread

In [3]:
df=pd.read_csv('Chicago_Crimes_2012_to_2017.csv')

In [4]:
df.head()

Unnamed: 0        ID Case Number                    Date  \
0           3  10508693    HZ250496  05/03/2016 11:40:00 PM   
1          89  10508695    HZ250409  05/03/2016 09:40:00 PM   
2         197  10508697    HZ250503  05/03/2016 11:31:00 PM   
3         673  10508698    HZ250424  05/03/2016 10:10:00 PM   
4         911  10508699    HZ250455  05/03/2016 10:00:00 PM   

                 Block  IUCR            Primary Type              Description  \
0   013XX S SAWYER AVE  0486                 BATTERY  DOMESTIC BATTERY SIMPLE   
1   061XX S DREXEL AVE  0486                 BATTERY  DOMESTIC BATTERY SIMPLE   
2  053XX W CHICAGO AVE  0470  PUBLIC PEACE VIOLATION         RECKLESS CONDUCT   
3    049XX W FULTON ST  0460                 BATTERY                   SIMPLE   
4    003XX N LOTUS AVE  0820                   THEFT           $500 AND UNDER   

  Location Description  Arrest  Domestic  Beat  District  Ward  \
0            APARTMENT    True      True  1022      10.0  24.0   
1            RESIDENCE   False      True   313       3.0  20.0   
2               STREET   False     False  1524      15.0  37.0   
3             SIDEWALK   False     False  1532      15.0  28.0   
4            RESIDENCE   False      True  1523      15.0  28.0   

   Community Area FBI Code  X Coordinate  Y Coordinate  Year  \
0            29.0      08B     1154907.0     1893681.0  2016   
1            42.0      08B     1183066.0     1864330.0  2016   
2            25.0       24     1140789.0     1904819.0  2016   
3            25.0      08B     1143223.0     1901475.0  2016   
4            25.0       06     1139890.0     1901675.0  2016   

               Updated On   Latitude  Longitude                       Location  
0  05/10/2016 03:56:50 PM  41.864073 -87.706819  (41.864073157, -87.706818608)  
1  05/10/2016 03:56:50 PM  41.782922 -87.604363   (41.782921527, -87.60436317)  
2  05/10/2016 03:56:50 PM  41.894908 -87.758372  (41.894908283, -87.758371958)  
3  05/10/2016 03:56:50 PM  41.885687 -87.749516  (41.885686845, -87.749515983)  
4  05/10/2016 03:56:50 PM  41.886297 -87.761751  (41.886297242, -87.761750709)

In [11]:
df_2016.shape

(250732, 24)

In [ ]:
df=df.dropna()

In [ ]:
df.shape

In [ ]:
df_2017.to_csv('chicago_crimes_2017.csv')

In [ ]:
df_2017=df.loc[df['Year']==2017]


In [ ]:
df_2016=df.loc[df['Year']==2016]

In [6]:
df_2016=pd.read_csv('chicago_crimes_2016.csv')

In [7]:
df_2016_1000=df_2016.loc[1:1000,:]

In [8]:
df_2016_1000=df_2016_1000.drop(['Unnamed: 0','Unnamed: 0.1'],axis=1)

In [13]:
from kmodes.kmodes import KModes

kclusters = 20
# df_new=df.drop(['Location','Date','Updated On','Location Description'],axis=1)
# df_new.drop(df_new.loc[df_new['Primary Type']=='OTHER WEAPONS VIOLATION'].index, inplace=True)
# run k-means clustering
kmeans = KModes(n_clusters=kclusters, random_state=42).fit(df_2016_1000)
# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:201]

array([ 1, 18,  1,  0,  7,  8,  8,  8,  1, 16,  1, 10,  0,  6,  1,  6,  9,
       11,  1,  3,  3,  6,  0,  4,  0,  0, 10, 10, 11, 11,  8,  0,  6,  2,
        8,  0,  2,  6,  1,  0, 11,  2,  5,  0,  2, 11, 11,  5, 11,  0,  4,
        1,  4,  6, 12, 14, 18, 12, 12,  2,  5, 13, 10,  6,  0,  3,  2, 10,
       11,  5,  0,  8,  6,  0,  3,  0,  9,  1,  8,  6, 11,  5,  5,  4, 15,
        3,  1,  6, 10,  3, 13, 18, 15,  5,  4,  4, 15,  4,  6, 13,  2,  8,
        0, 10, 12,  0,  2, 10,  1, 18,  4,  9, 11,  0, 12,  4,  0,  6,  8,
        1, 12, 12, 13,  2, 17, 10, 11,  1, 12,  4,  4,  0,  0,  4,  3, 18,
        5,  0, 10,  2,  0,  5,  0, 10,  5,  9,  0,  5,  6, 15,  6,  9, 15,
        1,  1, 16,  3,  7,  3,  7,  1,  3,  1, 12,  1,  9,  9,  9,  9,  9,
        9,  5, 15, 12, 15,  0, 12,  1,  5, 16,  3,  8, 10,  8,  9,  1,  1,
        1,  4,  9, 17,  4, 15,  1,  9,  2,  0,  7, 12, 13,  2],
      dtype=uint16)

In [9]:
from geopy.geocoders import Nominatim

address = 'Chicago, Il'

geolocator = Nominatim(user_agent="bg_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of Chicago City are {}, {}.'.format(latitude, longitude))

The geograpical coordinate of Chicago City are 41.8755616, -87.6244212.


In [10]:
# create map of New York using latitude and longitude values
map_bnglr = folium.Map(location=[latitude, longitude], zoom_start=10)

# add markers to map
for lat, lng, block in zip(df_2016_1000['Latitude'], df_2016_1000['Longitude'], df_2016_1000['Block']):
    label = '{}'.format(block)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_bnglr)  
    
map_bnglr

In [16]:
# create map
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(df_2016_1000['Latitude'], df_2016_1000['Longitude'],df_2016_1000['Block'], df_2016_1000['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[int(cluster)-1],
        fill=True,
        fill_color=rainbow[int(cluster)-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

In [15]:
# add clustering labels
df_2016_1000.insert(0, 'Cluster Labels', kmeans.labels_)

In [73]:
df_2016_1000.to_csv('df_2016_1000_cluster',index=False)

In [74]:
df_2016_1000_cluster=pd.read_csv('df_2016_1000_cluster')

In [75]:
df_2016_1000_cluster.head()

Cluster Labels        ID Case Number                    Date  \
0               1  10508695    HZ250409  05/03/2016 09:40:00 PM   
1              18  10508697    HZ250503  05/03/2016 11:31:00 PM   
2               1  10508698    HZ250424  05/03/2016 10:10:00 PM   
3               0  10508699    HZ250455  05/03/2016 10:00:00 PM   
4               7  10508702    HZ250447  05/03/2016 10:35:00 PM   

                  Block  IUCR            Primary Type  \
0    061XX S DREXEL AVE  0486                 BATTERY   
1   053XX W CHICAGO AVE  0470  PUBLIC PEACE VIOLATION   
2     049XX W FULTON ST  0460                 BATTERY   
3     003XX N LOTUS AVE  0820                   THEFT   
4  082XX S MARYLAND AVE  041A                 BATTERY   

               Description Location Description  Arrest  Domestic  Beat  \
0  DOMESTIC BATTERY SIMPLE            RESIDENCE   False      True   313   
1         RECKLESS CONDUCT               STREET   False     False  1524   
2                   SIMPLE             SIDEWALK   False     False  1532   
3           $500 AND UNDER            RESIDENCE   False      True  1523   
4      AGGRAVATED: HANDGUN               STREET   False     False   631   

   District  Ward  Community Area FBI Code  X Coordinate  Y Coordinate  Year  \
0       3.0  20.0            42.0      08B     1183066.0     1864330.0  2016   
1      15.0  37.0            25.0       24     1140789.0     1904819.0  2016   
2      15.0  28.0            25.0      08B     1143223.0     1901475.0  2016   
3      15.0  28.0            25.0       06     1139890.0     1901675.0  2016   
4       6.0   8.0            44.0      04B     1183336.0     1850642.0  2016   

               Updated On   Latitude  Longitude                       Location  
0  05/10/2016 03:56:50 PM  41.782922 -87.604363   (41.782921527, -87.60436317)  
1  05/10/2016 03:56:50 PM  41.894908 -87.758372  (41.894908283, -87.758371958)  
2  05/10/2016 03:56:50 PM  41.885687 -87.749516  (41.885686845, -87.749515983)  
3  05/10/2016 03:56:50 PM  41.886297 -87.761751  (41.886297242, -87.761750709)  
4  05/10/2016 03:56:50 PM  41.745354 -87.603799  (41.745354023, -87.603798903)

In [76]:
df_2016_1000_cluster=pd.read_csv('df_2016_1000_cluster')

In [77]:
df_2016_1000_cluster.head(100)

Cluster Labels        ID Case Number                    Date  \
0                1  10508695    HZ250409  05/03/2016 09:40:00 PM   
1               18  10508697    HZ250503  05/03/2016 11:31:00 PM   
2                1  10508698    HZ250424  05/03/2016 10:10:00 PM   
3                0  10508699    HZ250455  05/03/2016 10:00:00 PM   
4                7  10508702    HZ250447  05/03/2016 10:35:00 PM   
5                8  10508703    HZ250489  05/03/2016 10:30:00 PM   
6                8  10508704    HZ250514  05/03/2016 09:30:00 PM   
7                8  10508709    HZ250523  05/03/2016 04:00:00 PM   
8                1  10508982    HZ250667  05/03/2016 10:30:00 PM   
9               16  10508710    HZ250469  05/03/2016 09:44:00 PM   
10               1  10508715    HZ250541  05/03/2016 11:11:00 PM   
11              10  10508717    HZ250415  05/03/2016 05:30:00 PM   
12               0  10508724    HZ250513  05/03/2016 09:00:00 AM   
13               6  10508728    HZ250505  05/03/2016 10:08:00 PM   
14               1  10508732    HZ250535  05/03/2016 04:00:00 PM   
15               6  10508738    HZ250440  05/03/2016 09:45:00 PM   
16               9  10508741    HZ250587  05/03/2016 10:00:00 PM   
17              11  10508747    HZ250577  05/03/2016 08:00:00 PM   
18               1  10508752    HZ250500  05/03/2016 11:00:00 PM   
19               3  10508755    HZ250531  05/03/2016 11:37:00 PM   
20               3  10508757    HZ250601  05/03/2016 01:30:00 PM   
21               6  10508987    HZ250698  05/03/2016 06:30:00 PM   
22               0  10509011    HZ250748  05/03/2016 09:00:00 PM   
23               4  10509016    HZ250610  05/03/2016 11:30:00 PM   
24               0  10509030    HZ250659  05/03/2016 07:00:00 AM   
25               0  10509071    HZ250713  05/03/2016 08:30:00 PM   
26              10  10509077    HZ250776  05/03/2016 12:01:00 AM   
27              10  10509078    HZ250611  05/03/2016 12:01:00 AM   
28              11  10509094    HZ250662  05/03/2016 11:00:00 PM   
29              11  10509096    HZ250700  05/03/2016 04:45:00 PM   
..             ...       ...         ...                     ...   
70               0  10509694    HZ251105  05/03/2016 02:00:00 PM   
71               8  10509700    HZ249871  05/03/2016 03:05:00 PM   
72               6  10509702    HZ251095  05/03/2016 09:00:00 AM   
73               0  10509709    HZ251194  05/03/2016 12:30:00 AM   
74               3  10509724    HZ251141  05/03/2016 09:35:00 PM   
75               0  10509764    HZ249689  05/03/2016 12:15:00 PM   
76               9  10509769    HZ251010  05/03/2016 08:30:00 PM   
77               1  10509770    HZ250329  05/03/2016 09:00:00 AM   
78               8  10509783    HZ251242  05/03/2016 12:15:00 PM   
79               6  10509784    HZ251276  05/03/2016 08:00:00 PM   
80              11  10509800    HZ251202  05/03/2016 10:00:00 PM   
81               5  10509460    HZ250952  05/04/2016 11:30:00 AM   
82               5  10509801    HZ251260  05/03/2016 07:15:00 PM   
83               4  10509473    HZ250866  05/04/2016 09:00:00 AM   
84              15  10509840    HZ251384  05/03/2016 04:00:00 PM   
85               3  10509474    HZ250988  05/04/2016 08:16:00 AM   
86               1  10509843    HZ251265  05/03/2016 09:00:00 AM   
87               6  10509477    HZ250966  05/04/2016 05:00:00 AM   
88              10  10509846    HZ251231  05/03/2016 06:00:00 PM   
89               3  10509478    HZ250992  05/04/2016 11:58:00 AM   
90              13  10509480    HZ251028  05/04/2016 12:35:00 PM   
91              18  10509883    HZ251248  05/03/2016 07:15:00 PM   
92              15  10509896    HZ251520  05/03/2016 10:30:00 PM   
93               5  10509902    HZ251508  05/03/2016 08:40:00 PM   
94               4  10509920    HZ251426  05/03/2016 06:30:00 PM   
95               4  10509930    HZ251521  05/03/2016 10:00:00 PM   
96              15  10509946    HZ251516  05/03/2016 10:30:0

In [42]:
out=df.loc[df.ID==10512915]

In [43]:
out=out.drop(['Unnamed: 0'],axis=1)

In [44]:
out

ID Case Number                    Date              Block IUCR  \
1983  10512915              05/06/2016 09:15:00 PM  023XX W TAYLOR ST        

     Primary Type Description Location Description  Arrest  Domestic  Beat  \
1983                                    RESTAURANT   False     False  1225   

      District  Ward  Community Area FBI Code  X Coordinate  Y Coordinate  \
1983      12.0  25.0            28.0              1160966.0     1895521.0   

      Year              Updated On   Latitude  Longitude  \
1983  2016  05/13/2016 03:51:16 PM  41.868999 -87.684525   

                           Location  
1983  (41.868998803, -87.684525154)

In [40]:
df.loc[df.ID == 10512915, ['Case Number','IUCR','Primary Type', 'Description','FBI Code']] = '','','','',''


In [41]:
df.loc[df.ID==10512915]

Unnamed: 0        ID Case Number                    Date  \
1983      449178  10512915              05/06/2016 09:15:00 PM   

                  Block IUCR Primary Type Description Location Description  \
1983  023XX W TAYLOR ST                                         RESTAURANT   

      Arrest  Domestic  Beat  District  Ward  Community Area FBI Code  \
1983   False     False  1225      12.0  25.0            28.0            

      X Coordinate  Y Coordinate  Year              Updated On   Latitude  \
1983     1160966.0     1895521.0  2016  05/13/2016 03:51:16 PM  41.868999   

      Longitude                       Location  
1983 -87.684525  (41.868998803, -87.684525154)

In [45]:
kmeans.predict(out)

array([10], dtype=uint16)

In [51]:
one=df_2016_1000.loc[df_2016_1000['Cluster Labels']==10]

In [52]:
one.shape

(47, 23)

In [48]:
one.loc[one['Primary Type']=="THEFT"]

Cluster Labels        ID Case Number                    Date  \
12               10  10508717    HZ250415  05/03/2016 05:30:00 PM   
401              10  10509888    HZ251429  05/04/2016 05:00:00 PM   
419              10  10509950    HZ251461  05/04/2016 05:20:00 PM   

                    Block  IUCR Primary Type    Description  \
12   011XX W JACKSON BLVD  0890        THEFT  FROM BUILDING   
401  011XX W JACKSON BLVD  0860        THEFT   RETAIL THEFT   
419  011XX W JACKSON BLVD  0860        THEFT   RETAIL THEFT   

    Location Description  Arrest  Domestic  Beat  District  Ward  \
12                 OTHER   False     False  1232      12.0   2.0   
401     DEPARTMENT STORE    True     False  1232      12.0   2.0   
419   GROCERY FOOD STORE   False     False  1232      12.0   2.0   

     Community Area FBI Code  X Coordinate  Y Coordinate  Year  \
12             28.0       06     1168776.0     1898793.0  2016   
401            28.0       06     1168933.0     1898798.0  2016   
419            28.0       06     1168933.0     1898798.0  2016   

                 Updated On   Latitude  Longitude  \
12   05/10/2016 03:56:50 PM  41.877812 -87.655758   
401  05/11/2016 03:50:55 PM  41.877822 -87.655181   
419  05/11/2016 03:50:55 PM  41.877822 -87.655181   

                          Location  
12   (41.877811861, -87.655758012)  
401  (41.877822179, -87.655181405)  
419  (41.877822179, -87.655181405)

In [7]:
df_2016_1000=df_2016_1000.drop(['Unnamed: 0','Unnamed: 0.1'],axis=1)

In [8]:
df_2016_1000.head()

ID Case Number                    Date                 Block  IUCR  \
1  10508695    HZ250409  05/03/2016 09:40:00 PM    061XX S DREXEL AVE  0486   
2  10508697    HZ250503  05/03/2016 11:31:00 PM   053XX W CHICAGO AVE  0470   
3  10508698    HZ250424  05/03/2016 10:10:00 PM     049XX W FULTON ST  0460   
4  10508699    HZ250455  05/03/2016 10:00:00 PM     003XX N LOTUS AVE  0820   
5  10508702    HZ250447  05/03/2016 10:35:00 PM  082XX S MARYLAND AVE  041A   

             Primary Type              Description Location Description  \
1                 BATTERY  DOMESTIC BATTERY SIMPLE            RESIDENCE   
2  PUBLIC PEACE VIOLATION         RECKLESS CONDUCT               STREET   
3                 BATTERY                   SIMPLE             SIDEWALK   
4                   THEFT           $500 AND UNDER            RESIDENCE   
5                 BATTERY      AGGRAVATED: HANDGUN               STREET   

   Arrest  Domestic  Beat  District  Ward  Community Area FBI Code  \
1   False      True   313       3.0  20.0            42.0      08B   
2   False     False  1524      15.0  37.0            25.0       24   
3   False     False  1532      15.0  28.0            25.0      08B   
4   False      True  1523      15.0  28.0            25.0       06   
5   False     False   631       6.0   8.0            44.0      04B   

   X Coordinate  Y Coordinate  Year              Updated On   Latitude  \
1     1183066.0     1864330.0  2016  05/10/2016 03:56:50 PM  41.782922   
2     1140789.0     1904819.0  2016  05/10/2016 03:56:50 PM  41.894908   
3     1143223.0     1901475.0  2016  05/10/2016 03:56:50 PM  41.885687   
4     1139890.0     1901675.0  2016  05/10/2016 03:56:50 PM  41.886297   
5     1183336.0     1850642.0  2016  05/10/2016 03:56:50 PM  41.745354   

   Longitude                       Location  
1 -87.604363   (41.782921527, -87.60436317)  
2 -87.758372  (41.894908283, -87.758371958)  
3 -87.749516  (41.885686845, -87.749515983)  
4 -87.761751  (41.886297242, -87.761750709)  
5 -87.603799  (41.745354023, -87.603798903)

In [44]:
df_2016_1000=df_2016.loc[1:1000,:]

In [54]:
df_2016_1000_X=df_2016_1000.drop (['Case Number','IUCR','Primary Type','Description','FBI Code'],axis=1)

In [55]:
df_2016_1000_y=df_2016_1000.loc[:,['Primary Type']]

In [ ]:
--------------

In [ ]:
X=df_2016_1000_.loc[:, df_2016_1000.columns != 'Primary Type'].values

In [ ]:
y=df_2016_1000.iloc[:,6].values

In [ ]:
X

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=100)
classifier.fit(X_train, y_train)

In [57]:
features_X = pd.get_dummies(df_2016_1000_X)

In [58]:
features_y = pd.get_dummies(df_2016_1000_y)

In [59]:
import numpy as np
labels = np.array(features_y)
feature_list = list(features_X.columns)
features = np.array(features_X)

In [60]:
from sklearn.model_selection import train_test_split
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25, random_state = 42)

In [22]:
arr2D.shape
#arr2D = np.delete(test_features, [2018,2019], axis=1)

(750, 7017)

In [62]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators = 10000, random_state = 42)
rf.fit(train_features, train_labels);

In [ ]:
import pickle as cPickle
pkl_filename = "chicago_crime_2016_1000_split.pkl"
with open(pkl_filename, 'wb') as file:
    pickle.dump(rf, file)


# in your prediction file                                                                                                                                                                                                           

# with open('chicago_crime_2016_1000_split.pkl', 'rb') as f:
#     rf = cPickle.load(f)


# preds = rf.predict(new_X)

In [63]:
predicted=rf.predict(test_features)

In [65]:
test_labels

array([[0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [64]:
np.argmax(predicted,axis=1)

array([ 1,  6,  6, 21, 21,  4, 21,  1, 13, 15,  1, 18,  1,  4, 21,  1, 21,
        6, 18, 15,  1,  2,  0, 13,  0, 21,  1,  1, 21,  0, 21,  4,  4, 15,
        0,  4,  4, 21, 21,  4,  5,  2,  1, 21, 21, 15, 15, 12,  0,  0,  1,
        1,  1, 12, 21,  1, 21,  1,  1, 21, 21,  4,  1,  0,  1,  1, 21, 15,
       21, 21,  6,  1, 21, 21,  1,  4, 21, 21, 15, 21, 21,  4, 21,  6,  0,
        1, 21,  6, 21,  1,  1,  0, 12,  1,  4,  4, 21,  6, 21,  0,  4, 21,
        4, 18, 21, 21,  1,  0, 18,  0,  0,  6,  0, 18,  1, 22, 18, 21,  0,
        1, 21, 15, 12,  0, 21, 21,  2, 16, 13,  6,  2,  1,  4,  1, 21, 21,
        4,  4, 21, 21,  4, 12, 14,  0, 18,  1,  0, 21, 12,  1, 21,  0,  1,
        1,  4,  4, 21, 13, 15, 13, 15,  6, 12, 21, 21, 15,  1,  4,  1, 15,
       13,  1, 21,  4,  1, 13,  1,  1, 18,  6, 15, 21, 15,  1,  6, 21,  1,
       15, 21,  6, 13, 21, 14, 21,  0,  1,  4,  1, 21,  1, 12,  1, 13, 13,
       15,  4, 18,  1,  1,  1,  0, 15,  1, 21, 21, 21, 15, 13,  1, 22, 21,
        0, 12, 21, 12,  1

In [66]:
test_features

array([[1, 10510157, True, ..., 0, 0, 0],
       [10, 10515173, False, ..., 0, 0, 0],
       [10, 10515263, False, ..., 0, 0, 0],
       ...,
       [1, 10509770, False, ..., 0, 0, 0],
       [15, 10509840, False, ..., 0, 0, 0],
       [9, 10509327, False, ..., 0, 0, 0]], dtype=object)

In [72]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, roc_auc_score, roc_curve, f1_score

In [73]:
accuracy_score(test_labels, b)

0.772

In [67]:
b = np.zeros_like(predicted)

In [68]:
b[np.arange(len(predicted)), predicted.argmax(1)] = 1

In [70]:
b

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [59]:
test_labels

array([[0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [72]:
test=df_2016_1000_X.loc[df_2016_1000_X.ID==10508695,:]

In [74]:
test=pd.get_dummies(test)

In [75]:
test

Unnamed: 0  Unnamed: 0.1        ID  Arrest  Domestic  Beat  District  Ward  \
1           1            89  10508695   False      True   313       3.0  20.0   

   Community Area  X Coordinate  Y Coordinate  Year   Latitude  Longitude  \
1            42.0     1183066.0     1864330.0  2016  41.782922 -87.604363   

   Date_05/03/2016 09:40:00 PM  Block_061XX S DREXEL AVE  \
1                            1                         1   

   Location Description_RESIDENCE  Updated On_05/10/2016 03:56:50 PM  \
1                               1                                  1   

   Location_(41.782921527, -87.60436317)  
1                                      1

In [77]:
features_y

Primary Type_ASSAULT  Primary Type_BATTERY  Primary Type_BURGLARY  \
1                        0                     1                      0   
2                        0                     0                      0   
3                        0                     1                      0   
4                        0                     0                      0   
5                        0                     1                      0   
6                        0                     1                      0   
7                        0                     1                      0   
8                        0                     1                      0   
9                        0                     1                      0   
10                       0                     0                      0   
11                       0                     1                      0   
12                       0                     0                      0   
13                       0                     0                      0   
14                       0                     0                      0   
15                       0                     1                      0   
16                       0                     0                      0   
17                       0                     0                      0   
18                       0                     0                      0   
19                       0                     1                      0   
20                       1                     0                      0   
21                       1                     0                      0   
22                       0                     0                      0   
23                       0                     0                      0   
24                       0                     0                      0   
25                       0                     0                      0   
26                       0                     0                      0   
27                       0                     0                      0   
28                       0                     0                      0   
29                       0                     0                      0   
30                       0                     0                      0   
...                    ...                   ...                    ...   
971                      0                     0                      0   
972                      1                     0                      0   
973                      0                     0                      0   
974                      0                     0                      0   
975                      0                     0                      0   
976                      0                     0                      0   
977                      0                     0                      0   
978                      0                     1                      0   
979                      0                     0                      0   
980                      0                     0                      0   
981                      1                     0                      0   
982                      0                     0                      1   
983                      0                     0                      0   
984                      0                     0                      0   
985                      0                     0                      0   
986                      1                     0                      0   
987                      0                     1                      0   
988                      0                     0                      0   
989                      0                     0                      0   
990                      0                     0                      0   
991                      0                     0                      0   
992                      0     

In [76]:
df_2016.loc[df_2016.ID==10510157,:]

Unnamed: 0  Unnamed: 0.1        ID Case Number                    Date  \
522         557        155192  10510157    HZ251712  05/04/2016 09:35:00 PM   

                 Block  IUCR Primary Type              Description  \
522  086XX S TRIPP AVE  0486      BATTERY  DOMESTIC BATTERY SIMPLE   

    Location Description  Arrest  Domestic  Beat  District  Ward  \
522            RESIDENCE    True      True   834       8.0  18.0   

     Community Area FBI Code  X Coordinate  Y Coordinate  Year  \
522            70.0      08B     1149590.0     1847015.0  2016   

                 Updated On   Latitude  Longitude  \
522  05/11/2016 03:50:55 PM  41.736119 -87.727545   

                          Location  
522  (41.736119465, -87.727544585)